### ISSUE TITLE
Readability of code completion list is not good while using Dark Purple theme

### ISSUE THREAD

**Issue by ant-druha** [OlyaB/DarkPurpleTheme#18]
From https://youtrack.jetbrains.com/issue/IDEA-221801

Purple background + Gray foreground...
I think the color needs to be changed.

![image](https://user-images.githubusercontent.com/3117044/64117062-c8dc8c00-cd9c-11e9-93aa-087778023fac.png)
![image](https://user-images.githubusercontent.com/3117044/64117067-cbd77c80-cd9c-11e9-8ce6-794bf98c7aed.png)

**Comment by OlyaB** [comment]
Made the selection background a bit darker, this is the only improvement I can make using the theme json. There's no separate color key for the secondary text on selection.
