### ISSUE TITLE
The are no color schemes in the chosen file.

### ISSUE THREAD

**Issue by objcoding** [OlyaB/DarkPurpleTheme#2]
![image](https://user-images.githubusercontent.com/24354760/55204958-e31da700-520b-11e9-9516-b30bbfa248ac.png)

**Comment by OlyaB** [comment]
To install the custom theme, please follow instructions in the [README](https://github.com/OlyaB/DarkPurpleTheme/blob/master/README.md) file. Or you can install DarkPurpleTheme.jar manually in the Settings > Plugins page — click the cog icon to the right of the "Updated" tab and select "Install plugin from disk", then select the jar file.

The editor color scheme goes together with the custom theme. You will see it in the Editor > Color Scheme combobox once you install the theme plugin. If you need only the editor color scheme, you can install [darkPurpleScheme.xml](https://github.com/OlyaB/DarkPurpleTheme/blob/master/resources/themes/darkPurpleScheme.xml) the way you tried in Editor > Color Scheme page.

**Comment by objcoding** [comment]
thanks for your helps
