### ISSUE TITLE
invalid color in .theme.json file

### ISSUE THREAD

**Issue by DevCharly** [OlyaB/DarkPurpleTheme#20]
I'm using your .theme.json file in a Demo for a Swing look and feel
(https://github.com/JFormDesigner/FlatLaf) and found that there is
one invalid color in the json file.

~~~
"MenuBar.borderColor": "##1a1721"
~~~

https://github.com/OlyaB/DarkPurpleTheme/blob/master/src/DarkPurple.theme.json#L169

**Comment by OlyaB** [comment]
Thanks! Fixed
