### ISSUE TITLE
Theme looks partially incorrect in IDEA 2020.2

### ISSUE THREAD

**Issue by Jarzka** [OlyaB/DarkPurpleTheme#22]
I think these backgrounds were not grey before the update.

Branches list:

https://imgur.com/a/NQyw0sg

Global find:

https://imgur.com/a/xIA9QYt

**Comment by OlyaB** [comment]
Thank you for reporting! Backgrounds in these dialogs look alright to me in my IDEA 2020.2. Do you still experience this problem?

**Comment by Jarzka** [comment]
Yes, I'm still having this issue in the latest IDEA version (2020.2.3). It repeats on my Mac but not on my PC. I wonder if this has something to do with my settings. Is it possible to completely "reset" the plugin?

**Comment by Jarzka** [comment]
I updated the plugin to the latest version (1.2). It solved the issue. It seems that IDEA has not updated the plugin automatically.
