### ISSUE TITLE
This Theme not applying to Android Studio Arctic Fox...

### ISSUE THREAD

**Issue by asiimwedismas** [OlyaB/DarkPurpleTheme#26]

**Comment by moisoni97** [comment]
Apparently, it's an issue affecting all themes not only `DarkPurpleTheme`.
https://stackoverflow.com/questions/68572505/after-updating-to-android-studio-arctic-fox-i-cannot-use-any-custom-theme

**Comment by asiimwedismas** [comment]
thanks for the info, I hope they fix it soon

**Comment by moisoni97** [comment]
The issue is [fixed](https://issuetracker.google.com/issues/194925628) and will be included in the next minor release.

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037
